spring.application.name=persistence
server.port=8082
spring.rabbitmq.publisher-confirm-type=correlated
spring.rabbitmq.publisher-returns=true

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

spring.data.mongodb.uri=mongodb://localhost:27017/itau_challenge
spring.data.mongodb.uuid-representation=standard